# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-02 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171202_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
