# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20171122_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectguide',
            name='guide1',
        ),
        migrations.RemoveField(
            model_name='projectguide',
            name='guide2',
        ),
        migrations.AddField(
            model_name='projectguide',
            name='guide',
            field=models.ManyToManyField(to='portal.Guide'),
        ),
    ]
