# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171126_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Project'),
        ),
    ]
