# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-26 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20171126_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectguide',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='projectguide',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='guide',
            field=models.ManyToManyField(to='portal.Guide'),
        ),
        migrations.DeleteModel(
            name='ProjectGuide',
        ),
    ]
